name: Test
on:
    pull_request:
        paths: [typescript-project/**/*.ts]
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Install pnpm 
              uses: pnpm/action-setup@v2
              with:
                version: '8'
                run_install: false
            - name: Get pnpm store directory
              shell: bash
              run: |
                  echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
            - name: Cache pnpm store
              uses: actions/cache@v3
              with:
                  path: ${{ env.STORE_PATH }}
                  key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
                  restore-keys: |
                      ${{ runner.os }}-pnpm-store-
            - uses: actions/setup-node@v4
              with:
                node-version: '20'
                cache: pnpm
            - name: Install dependencies
              run: pnpm install
              working-directory: ./typescript-project
            - run: pnpm test
              working-directory: ./typescript-project