name: Test
on:
    pull_request:
        paths: [typescript-project/**/*.ts]
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                node-version: '20'
                cache: pnpm
            - name: Install pnpm 
              uses: pnpm/action-setup@v2
              with:
                version: '8'
            - name: Check for pnpm-lock.yaml
              run: ls -la typescript-project
            - name: Cache pnpm store
              uses: actions/cache@v3
              with:
                  path: ~/typescript-project/.pnpm-store
                  key: ${{ runner.os }}-pnpm-${{ hashFiles('typescript-project/pnpm-lock.yaml') }}
                  restore-keys: |
                    ${{ runner.os }}-pnpm-
            - name: Install dependencies
              run: pnpm install
              working-directory: ./typescript-project
            - run: pnpm test
              working-directory: ./typescript-project